github: [Brain-battle-S2]
patreon: patreon.com/CodingJunction
ko_fi: brainbattle2024
buy_me_a_coffee: brainbattle2024
custom: ['https://unstop.com/hackathons/brain-battle-season-2-coding-junction-1185487', 'https://www.brainbattle2024.tech']
