github: [Brain-battle-S2]
patreon: ['patreon.com/CodingJunction']
ko_fi: ['https://ko-fi.com/codingjunction']
buy_me_a_coffee: ['https://buymeacoffee.com/coding.junction']
custom: ['https://unstop.com/hackathons/brain-battle-season-2-coding-junction-1185487', 'https://www.brainbattle2024.tech']
